INSERT INTO riders (dorsal, name, team, category) values ( 41, 'Aleix Espargaró', 'Aprilia Racing', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 73, 'Álex Márquez', 'Gresini Racing MotoGP', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 42, 'Alex Rins', 'LCR Honda', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 37, 'Augusto Fernández', 'GasGas Factory Racing (Tech3)', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 33, 'Brad Binder', 'Red Bull KTM Factory', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 23, 'Enea Bastianini', 'Ducati Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 49, 'Fabio Di Giannantonio', 'Gresini Racing MotoGP', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 20, 'Fabio Quartararo', 'Monster Energy Yamaha', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 21, 'Franco Morbidelli', 'Monster Energy Yamaha', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 43, 'Jack Miller', 'Red Bull KTM Factory', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 36, 'Joan Mir', 'Repsol Honda Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 5, 'Johann Zarco', 'Pramac Racing', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 89, 'Jorge Martín', 'Pramac Racing', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 10, 'Luca Marini', 'VR46 Racing Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 93, 'Marc Márquez', 'Repsol Honda Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 72, 'Marco Bezzecchi', 'VR46 Racing Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 12, 'Maverick Viñales', 'Aprilia Racing', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 88, 'Miguel Oliveira', 'RNF MotoGP Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 63, 'Pecco Bagnaia', 'Ducati Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 44, 'Pol Espargaró', 'GasGas Factory Racing (Tech3)', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 25, 'Raúl Fernández', 'RNF MotoGP Team', 'MotoGP');
INSERT INTO riders (dorsal, name, team, category) values ( 30, 'Takaaki Nakagami', 'LCR Honda', 'MotoGP');
COMMIT;
INSERT INTO riders (dorsal, name, team, category) values ( 79, 'Ai Ogura', 'Idemitsu Honda Team Asia', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 75, 'Albert Arenas', 'Red Bull KTM Ajo', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 17, 'Alex Escrig', 'MV Agusta Forward Racing', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 21, 'Alonso Lopez', 'Speed Up Racing', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 40, 'Aron Canet', 'Flexbox HP40', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 7, 'Barry Baltus', 'RW Racing GP', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 64, 'Bo Bendsneyder', 'Pertamina Mandalika SAG Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 13, 'Celestino Vietti', 'Team Fanatic-VR46', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 15, 'Darryn Binder', 'Liqui Moly Husqvarna Factory Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 71, 'Dennis Foggia', 'Italtrans Racing Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 54, 'Fermin Aldeguer', 'Speed Up Racing', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 12, 'Filip Salac', 'Grasini Racing Moto2', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 28, 'Izan Guevara', 'GASGAS Aspar Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 96, 'Jake Dixon', 'GASGAS Aspar Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 52, 'Jeremy Alcoba', 'Grasini Racing Moto2', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 16, 'Joe Roberts', 'Italtrans Racing Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 5, 'Kohta Nozane', 'Yamaha VR46 Master Camp Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 19, 'Lorenzo Dalla Porta', 'Pertamina Mandalika SAG Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 3, 'Lukas Tulovic', 'Liqui Moly Husqvarna Factory Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 18, 'Manuel González', 'Yamaha VR46 Master Camp Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 24, 'Marcos Ramirez', 'MV Agusta Forward Racing', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 23, 'Niccolo Antonelli', 'Team Fanatic-VR46', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 37, 'Pedro Acosta', 'Red Bull KTM Ajo', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 33, 'Rory Skinner', 'American Racing', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 22, 'Sam Lowes', 'Elf Marc VDS Racing Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 4, 'Sean Dylan Kelly', 'American Racing', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 11, 'Sergio Garcia', 'Flexbox HP40', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 35, 'Somkiat Chantra', 'Idemitsu Honda Team Asia', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 14, 'Tony Arbolino', 'Elf Marc VDS Racing Team', 'Moto2');
INSERT INTO riders (dorsal, name, team, category) values ( 84, 'Zonta van den Goorbergh', 'RW Racing GP', 'Moto2');
COMMIT;
INSERT INTO riders (dorsal, name, team, category) values ( 22, 'Ana Carrasco', 'Boé Motorsports ', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 71, 'Ayumu Sasaki', 'Liqui Moly Husqvarna Intact GP', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 95, 'Colin Viejer', 'Liqui Moly Husqvarna Intact GP', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 96, 'Daniel Holgado', 'Red Bull KTM Tech3', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 80, 'David Alonso', 'GasGas Aspar Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 44, 'David Muñoz', 'Boé Motorsports ', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 38, 'David Salvador', 'CIP Green Power', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 53, 'Deniz Öncü', 'Red Bull KTM Ajo', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 10, 'Diogo Moreira', 'MT Helmets - MSI', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 7, 'Filippo Farioli', 'Red Bull KTM Tech3', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 48, 'Iván Ortolá', 'Angeluss MTA Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 5, 'Jaume Masià', 'Leopard Racing', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 66, 'Joel Kelso', 'CFMoto Racing Prüstel GP', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 99, 'José Antonio Rueda', 'Red Bull KTM Ajo', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 70, 'Josh Whatley', 'VisionTrack Racing Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 27, 'Kaito Toba', 'Sic58 Squadra Corse', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 20, 'Lorenzo Fellon', 'CIP Green Power', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 64, 'Mario Aji', 'Honda Team Asia', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 18, 'Matteo Bertelle', 'Rivacold Snipers Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 54, 'Riccardo Rossi', 'Sic58 Squadra Corse', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 55, 'Romano Fenati', 'Rivacold Snipers Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 6, 'Ryusei Yamanaka', 'GasGas Aspar Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 19, 'Scott Ogden', 'VisionTrack Racing Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 82, 'Stefano Nepa', 'Angeluss MTA Team', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 63, 'Syarifuddin Azman', 'MT Helmets - MSI', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 72, 'Taiyo Furusato', 'Honda Team Asia', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 24, 'Tatsuki Suzuki', 'Leopard Racing', 'Moto3');
INSERT INTO riders (dorsal, name, team, category) values ( 43, 'Xavier Artigas', 'CFMoto Racing Prüstel GP', 'Moto3');
COMMIT;