CREATE TABLE "public"."bets"(

    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,

    "moto2" CHARACTER VARYING(255),

    "moto3" CHARACTER VARYING(255),

    "motogp_5" CHARACTER VARYING(255),

    "motogp_1" CHARACTER VARYING(255),

    "motogp_4" CHARACTER VARYING(255),

    "motogp_2" CHARACTER VARYING(255),

    "motogp_6" CHARACTER VARYING(255),

    "motogp_3" CHARACTER VARYING(255),

    "result" BOOLEAN,

    "race_id" BIGINT,

    "team_id" BIGINT

);
ALTER TABLE "public"."bets" ADD CONSTRAINT "CONSTRAINT_1" PRIMARY KEY("id");
-- 0 +/- SELECT COUNT(*) FROM public.bets;

CREATE TABLE "public"."classification"(

                                          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

                                          "bonification_gp_points" INTEGER,

                                          "earned" DOUBLE PRECISION,

                                          "entry_points" INTEGER,

                                          "moto_two_and_three_points" INTEGER,

                                          "position" INTEGER,

                                          "position_points" INTEGER,

                                          "total_gp_points" INTEGER,

                                          "total_points" INTEGER,

                                          "race_id" BIGINT,

                                          "team_id" BIGINT

);
ALTER TABLE "public"."classification" ADD CONSTRAINT "CONSTRAINT_9" PRIMARY KEY("id");
-- 44 +/- SELECT COUNT(*) FROM public.classification;
CREATE TABLE "public"."configuration"(

                                         "clave" CHARACTER VARYING(255) NOT NULL,

                                         "valor" CHARACTER VARYING(255)

);
ALTER TABLE "public"."configuration" ADD CONSTRAINT "CONSTRAINT_2" PRIMARY KEY("clave");
-- 1 +/- SELECT COUNT(*) FROM public.configuration;
CREATE TABLE "public"."races"(

                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

                                 "country" CHARACTER VARYING(255),

                                 "end_date" TIMESTAMP,

                                 "name" CHARACTER VARYING(255),

                                 "open" BOOLEAN,

                                 "season" INTEGER,

                                 "start_date" TIMESTAMP

);
ALTER TABLE "public"."races" ADD CONSTRAINT "CONSTRAINT_4" PRIMARY KEY("id");
-- 22 +/- SELECT COUNT(*) FROM public.races;
CREATE TABLE "public"."riders"(

                                  "category" CHARACTER VARYING(255) NOT NULL,

                                  "dorsal" BIGINT NOT NULL,

                                  "name" CHARACTER VARYING(255),

                                  "team" CHARACTER VARYING(255)

);
ALTER TABLE "public"."riders" ADD CONSTRAINT "CONSTRAINT_90" PRIMARY KEY("category", "dorsal");
-- 80 +/- SELECT COUNT(*) FROM public.riders;
CREATE TABLE "public"."teams"(

                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,

                                 "name" CHARACTER VARYING(255),

                                 "total_earned" INTEGER

);
ALTER TABLE "public"."teams" ADD CONSTRAINT "CONSTRAINT_4C" PRIMARY KEY("id");
-- 2 +/- SELECT COUNT(*) FROM public.teams;
CREATE TABLE "public"."users"(

                                 "username" CHARACTER VARYING(255) NOT NULL,

                                 "password" CHARACTER VARYING(255),

                                 "role" CHARACTER VARYING(255),

                                 "team_id" BIGINT

);
ALTER TABLE "public"."users" ADD CONSTRAINT "CONSTRAINT_4D" PRIMARY KEY("username");
-- 2 +/- SELECT COUNT(*) FROM public.users;
ALTER TABLE "public"."bets" ADD CONSTRAINT "UNIQUEBETteamRACE" UNIQUE("team_id", "race_id");
ALTER TABLE "public"."classification" ADD CONSTRAINT "UNIQUECLASSIFIEDteamRACE" UNIQUE("team_id", "race_id");
ALTER TABLE "public"."classification" ADD CONSTRAINT "FKFWVQKF2QQELE45HGLI9K9MC6O" FOREIGN KEY("team_id") REFERENCES "public"."teams"("id");
ALTER TABLE "public"."bets" ADD CONSTRAINT "FKGI77N8PBWJ6SEFHOR9JS3IPGT" FOREIGN KEY("race_id") REFERENCES "public"."races"("id");
ALTER TABLE "public"."bets" ADD CONSTRAINT "FKEIAHIYCH1INAGKI6DM1MW39X1" FOREIGN KEY("team_id") REFERENCES "public"."teams"("id");
ALTER TABLE "public"."classification" ADD CONSTRAINT "FKLGBC2KINCD3MHIH5MV3A48KX8" FOREIGN KEY("race_id") REFERENCES "public"."races"("id");
ALTER TABLE "public"."users" ADD CONSTRAINT "FKFJWS1RDRUAB2BQG7QIPOQF65R" FOREIGN KEY("team_id") REFERENCES "public"."teams"("id");


COMMIT;